version: '3.1'
services:
  db: 
    image: 'postgres:17'
    ports: 
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_POSSWORD: 123
      POSTGRES_DB: nest
    networks:
      - tutor

networks:
  tutor:


